version: "3.3"
services:
  web:
    container_name: lottrading
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
#      - API_HOST=http://app:8080
#    networks:
#      - default
    #restart: always
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Danila2012
      - POSTGRES_USER=postgres
      - POSTGRES_DB=qligent
    #restart: always
#networks:
#  default:
#    driver: bridge

volumes:
  postgres-data:
    driver: local