version: "3.3"
services:
  web:
    container_name: lottrading
    build: ./
    ports:
      - "9081:8080"
      - "5050:5050"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
    #restart: always
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Danila2012
      - POSTGRES_USER=postgres
      - POSTGRES_DB=qligent
    #restart: always

volumes:
  postgres-data:
    driver: local